import express from "express";
import authRoutes from "./auth.routes.js";
import healthRoutes from "./health.routes.js";
import connectionsRoutes from "./connections.routes.js";
import catalogRoutes from "./catalog.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import monitorRoutes from "./monitor.routes.js";
import qualityRoutes from "./quality.routes.js";
import governanceRoutes from "./governance.routes.js";
import monitoringRoutes from "./monitoring.routes.js";
import governanceCatalogRoutes from "./governance-catalog.routes.js";
import configRoutes from "./config.routes.js";
import logsRoutes from "./logs.routes.js";
import securityRoutes from "./security.routes.js";
import apiCatalogRoutes from "./api-catalog.routes.js";
import csvCatalogRoutes from "./csv-catalog.routes.js";
import dataLineageRoutes from "./data-lineage.routes.js";
import workflowsRoutes from "./workflows.routes.js";
import dbtRoutes from "./dbt.routes.js";
import bigDataRoutes from "./big-data.routes.js";
import streamProcessingRoutes from "./stream-processing.routes.js";
import performanceRoutes from "./performance.routes.js";
import metadataRoutes from "./metadata.routes.js";
import alertRulesRoutes from "./alert-rules.routes.js";
import transformationsRoutes from "./transformations.routes.js";
import customJobsRoutes from "./custom-jobs.routes.js";
import schemaMigrationsRoutes from "./schema-migrations.routes.js";
import schemaChangesRoutes from "./schema-changes.routes.js";
import queryPerformanceRoutes from "./query-performance.routes.js";
import maintenanceRoutes from "./maintenance.routes.js";
import catalogCleanerRoutes from "./catalog-cleaner.routes.js";
import columnCatalogRoutes from "./column-catalog.routes.js";
import catalogLocksRoutes from "./catalog-locks.routes.js";
import datalakeRoutes from "./datalake.routes.js";
import cdcRoutes from "./cdc.routes.js";
import unusedObjectsRoutes from "./unused-objects.routes.js";
import docsRoutes from "./docs.routes.js";
import backupsRoutes from "./backups.routes.js";
import dataMaskingRoutes from "./data-masking.routes.js";
import dataEncryptionRoutes from "./data-encryption.routes.js";
import rlsRoutes from "./rls.routes.js";
import auditRoutes from "./audit.routes.js";
import complianceRoutes from "./compliance.routes.js";
import dataClassifierRoutes from "./data-classifier.routes.js";
import dataRetentionRoutes from "./data-retention.routes.js";
import webhooksRoutes from "./webhooks.routes.js";

const router = express.Router();

// Register all routers
router.use("/auth", authRoutes);
router.use("/health", healthRoutes);
router.use("/connections", connectionsRoutes);
router.use("/catalog", catalogRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/monitor", monitorRoutes);
router.use("/quality", qualityRoutes);
router.use("/governance", governanceRoutes);
router.use("/monitoring", monitoringRoutes);
router.use("/governance-catalog", governanceCatalogRoutes);
router.use("/config", configRoutes);
router.use("/logs", logsRoutes);
router.use("/security", securityRoutes);
router.use("/api-catalog", apiCatalogRoutes);
router.use("/csv-catalog", csvCatalogRoutes);
router.use("/data-lineage", dataLineageRoutes);
router.use("/workflows", workflowsRoutes);
router.use("/dbt", dbtRoutes);
router.use("/big-data", bigDataRoutes);
router.use("/stream-processing", streamProcessingRoutes);
router.use("/performance", performanceRoutes);
router.use("/metadata", metadataRoutes);
router.use("/alert-rules", alertRulesRoutes);
router.use("/transformations", transformationsRoutes);
router.use("/custom-jobs", customJobsRoutes);
router.use("/schema-migrations", schemaMigrationsRoutes);
router.use("/schema-changes", schemaChangesRoutes);
router.use("/query-performance", queryPerformanceRoutes);
router.use("/maintenance", maintenanceRoutes);
router.use("/catalog-cleaner", catalogCleanerRoutes);
router.use("/column-catalog", columnCatalogRoutes);
router.use("/catalog-locks", catalogLocksRoutes);
router.use("/datalake", datalakeRoutes);
router.use("/cdc", cdcRoutes);
router.use("/unused-objects", unusedObjectsRoutes);
router.use("/backups", backupsRoutes);
router.use("/data-masking", dataMaskingRoutes);
router.use("/data-encryption", dataEncryptionRoutes);
router.use("/rls", rlsRoutes);
router.use("/audit", auditRoutes);
router.use("/compliance", complianceRoutes);
router.use("/data-classifier", dataClassifierRoutes);
router.use("/data-retention", dataRetentionRoutes);
router.use("/webhooks", webhooksRoutes);
router.use("/", docsRoutes);

export default router;
