export const asciiColors = {
  background: "#ffffff",
  backgroundSoft: "#f8f9fa",
  foreground: "#1a1a1a",
  muted: "#6b7280",
  border: "#d1d5db",
  borderStrong: "#9ca3af",
  accent: "#1e40af",
  accentSoft: "#3b82f6",
  accentLight: "#dbeafe",
  danger: "#dc2626",
  success: "#16a34a",
  warning: "#f59e0b",
};

export const ascii = {
  h: "─",
  v: "│",
  tl: "┌",
  tr: "┐",
  bl: "└",
  br: "┘",
  cross: "┼",
  tUp: "┴",
  tDown: "┬",
  tLeft: "┤",
  tRight: "├",
  thickH: "═",
  thickV: "║",
  thickTl: "╔",
  thickTr: "╗",
  thickBl: "╚",
  thickBr: "╝",
  bullet: "•",
  arrowRight: "▶",
  arrowDown: "▼",
  dot: "·",
  blockFull: "█",
  blockSemi: "▓",
  blockLight: "▒",
};
